INSERT INTO pcBuild 
        (
         pcBuild_name, 
         pcBuild_type,
         pcBuild_notes,
         pcBuild_avgPartAge,
         pcBuild_mobo_id,
         pcBuild_case_id,
         pcBuild_ram_id,
         pcBuild_gpu_id,
         pcBuild_ssd_id,
         pcBuild_hdd_id,
         pcBuild_cpu_id,
         pcBuild_psu_id,
         pcBuild_cpuCool_id,
         pcBuild_fan_id,
         pcBuild_ledkit_id,
         pcBuild_os_id,
         pcBuild_colorScheme
         ) 
        VALUES (
                ?, 
                ?, 
                ?, 
                ?, 
                ?, 
                ?, 
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?,
                ?
                )